### ISSUE TITLE
set pallete for PIL.Image

### ISSUE THREAD

**Issue by ege114366** [stashvala/VideoMatch#4]
In main.py line 422, the author wrote 
 # TODO: images are black even though class values are saved, maybe set pallete for PIL.Image.
I have no idea what the pallete means. Can anyone tell me more details about the pallete?

**Comment by stashvala** [comment]
When saving the evaluation output I noticed that the resulting segmentation image was all black, probably because it scales class values [0,1] to 0-255. By setting the pallete in `PIL.Image` you can set which colors should represent which classes, in our case [0, 1]. See [this SO post](https://stackoverflow.com/questions/67642262/python-image-types-shapes-and-channels-for-segmentation)

**Comment by ege114366** [comment]
Thanks!!
And I have one more problem,,,
In main.py line 350~388 (especially 377)

  for frames in data_loader:
        if next_seq_buff:
            frames = next_seq_buff + frames
            next_seq_buff = []
            print("here1")

        if curr_seq != frames[0].seq:
            # print(frames[0].seq)
            print("here2")
            # end of a sequence
            if curr_seq is not None:
                print("here22")
                process_results(curr_seq, segm_list, visualize, results_dir)

            # start of a (new) sequence
            curr_seq = frames[0].seq

            logger.debug("Evaluating sequence {}".format(curr_seq))
            ref_frame = frames[0]

            test_frames = frames[1:]

            segm_list = [np.array(ref_frame.ann)]
            ref_img = basic_img_transform(ref_frame.img, img_shape)
            ref_mask = basic_ann_transform(ref_frame.ann, img_shape)
     
            prev_mask = ref_mask

            vm.seq_init(ref_img, ref_mask)

        # presumes that batch size is smaller than min number of frames in smallest sequence
        else:
            print("here3")
            seq_names = [f.seq.name for f in frames]
            comp = [i for i, x in enumerate(seq_names) if curr_seq.name != x]

            # next sequence
            if comp:
                next_seq_buff = frames[comp[0]:]
                test_frames = frames[:comp[0]]
     
            # same sequence
            else:
                test_frames = frames

when i print the comp, it is [ ] and never go to the 
#next sequence 
if comp:
 next_seq_buff = frames[comp[0]:]
 test_frames = frames[:comp[0]]
so can you tell me what does the comp = [i for i, x in enumerate(seq_names) if curr_seq.name != x] means and how can I proceed to 
 if next_seq_buff:
            frames = next_seq_buff + frames
            next_seq_buff = []

Thanks for answer in advance
